// Auto-generated by scripts/generate-focus.ts — do not edit by hand.
// Recomputed on every `bun run dev` / `bun run build` from the last N merged
// branches that touched a projects/ directory (see that script for the "why").
export const GENERATED_FOCUS = {
  "id": "06",
  "tally": {
    "06": 5,
    "01": 1
  },
  "window": 6
} as const
