#!/usr/bin/env bun
/**
 * Computes "current focus" for the roadmap site from real git history instead
 * of a hand-edited constant.
 *
 * Naively using the single most-recently-merged branch is noisy: a one-off
 * merge (a CI fix, a dependency bump) that happens to touch a project's files
 * can flip "current focus" to a project nobody is actually working on. So
 * instead this looks at the last WINDOW *merges that actually touched a
 * project directory* and takes the plurality — one merge, one vote, tie
 * broken in favor of the more recent one. A single stray merge can't outvote
 * several real ones.
 *
 * Only first-parent merges are considered (`git log --first-parent --merges`)
 * so that "merge master into my feature branch" sync commits — which live on
 * the second-parent side of history — don't get counted as if they were their
 * own branch of work.
 *
 * Run via `bun run generate:focus` (wired into `dev`/`build`). Writes
 * site/src/data/focus.generated.ts, which roadmap.ts imports. The committed
 * copy of that file is just a last-known-good snapshot for anyone who reads
 * the repo without running the script; every dev/build run recomputes it.
 */
import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(SCRIPT_DIR, "..", "..");
const OUT_FILE = join(SCRIPT_DIR, "..", "src", "data", "focus.generated.ts");

/** How many project-touching merges to poll. */
const WINDOW = 10;
/** Safety cap on how far back to look for WINDOW qualifying merges. */
const MAX_MERGES_SCANNED = 60;

function git(args: string[]): string {
  return execFileSync("git", args, { cwd: REPO_ROOT, encoding: "utf8" }).trim();
}

/** 'projects/06-object-store/src/foo.rs' -> '06' */
function projectIdFromPath(path: string): string | null {
  return path.match(/^projects\/(\d+)-[^/]+\//)?.[1] ?? null;
}

type Vote = { hash: string; projectId: string };

/** Newest-first votes, one per merge that touched at least one projects/ path. */
function collectVotes(): Vote[] {
  let merges: string[];
  try {
    merges = git([
      "log",
      "--first-parent",
      "--merges",
      `-n${MAX_MERGES_SCANNED}`,
      "--pretty=format:%H",
    ])
      .split("\n")
      .filter(Boolean);
  } catch {
    return []; // not a git checkout, or git isn't on PATH
  }

  const votes: Vote[] = [];
  for (const hash of merges) {
    if (votes.length >= WINDOW) break;

    let files: string[];
    try {
      files = git(["diff", "--name-only", `${hash}^1..${hash}`])
        .split("\n")
        .filter(Boolean);
    } catch {
      continue; // e.g. a shallow checkout missing this merge's parents
    }

    const filesPerProject = new Map<string, number>();
    for (const file of files) {
      const id = projectIdFromPath(file);
      if (id) filesPerProject.set(id, (filesPerProject.get(id) ?? 0) + 1);
    }
    if (filesPerProject.size === 0) continue; // docs/CI/site-only merge — not project work, abstain

    // This merge's vote goes to whichever project it touched the most files in.
    const [topProjectId] = [...filesPerProject.entries()].sort((a, b) => b[1] - a[1])[0]!;
    votes.push({ hash, projectId: topProjectId });
  }
  return votes;
}

function pickFocus(
  votes: Vote[],
): { id: string; tally: Record<string, number>; window: number } | null {
  if (votes.length === 0) return null;

  const tally: Record<string, number> = {};
  for (const vote of votes) tally[vote.projectId] = (tally[vote.projectId] ?? 0) + 1;

  // votes[] is newest-first, so the first project to reach the max tally is
  // also the most recently active one — ties favor recency automatically.
  let winner = votes[0]!.projectId;
  let winnerCount = 0;
  for (const vote of votes) {
    if (tally[vote.projectId]! > winnerCount) {
      winnerCount = tally[vote.projectId]!;
      winner = vote.projectId;
    }
  }
  return { id: winner, tally, window: votes.length };
}

const focus = pickFocus(collectVotes());

writeFileSync(
  OUT_FILE,
  `// Auto-generated by scripts/generate-focus.ts — do not edit by hand.\n` +
    `// Recomputed on every \`bun run dev\` / \`bun run build\` from the last N merged\n` +
    `// branches that touched a projects/ directory (see that script for the "why").\n` +
    `export const GENERATED_FOCUS = ${focus ? JSON.stringify(focus, null, 2) : "null"} as const\n`,
);

if (focus) {
  console.log(
    `[generate-focus] current focus: ${focus.id} (${focus.tally[focus.id]}/${focus.window} recent project merges)`,
  );
} else {
  console.log(
    "[generate-focus] no project-touching merges found — falling back to FALLBACK_FOCUS in roadmap.ts",
  );
}
