# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import ratelimit_pb2 as ratelimit__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ratelimit_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RateLimiterStub:
    """A distributed rate-limiting service. Gateways and upstream services call
    `Check` before admitting a request; the limiter returns an allow/deny decision
    and reports how much of the budget remains. The decision must be cheap and
    fast — this sits on someone else's hot path.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Check = channel.unary_unary(
                '/ratelimit.v1.RateLimiter/Check',
                request_serializer=ratelimit__pb2.CheckRequest.SerializeToString,
                response_deserializer=ratelimit__pb2.CheckResponse.FromString,
                _registered_method=True)
        self.Peek = channel.unary_unary(
                '/ratelimit.v1.RateLimiter/Peek',
                request_serializer=ratelimit__pb2.PeekRequest.SerializeToString,
                response_deserializer=ratelimit__pb2.CheckResponse.FromString,
                _registered_method=True)


class RateLimiterServicer:
    """A distributed rate-limiting service. Gateways and upstream services call
    `Check` before admitting a request; the limiter returns an allow/deny decision
    and reports how much of the budget remains. The decision must be cheap and
    fast — this sits on someone else's hot path.
    """

    def Check(self, request, context):
        """Atomically account for one request against `key` and return the decision.
        Consumes `cost` tokens of budget when allowed.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Peek(self, request, context):
        """Report the current state for `key` WITHOUT consuming budget — for
        dashboards, debugging, and "am I about to be limited?" probes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RateLimiterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=ratelimit__pb2.CheckRequest.FromString,
                    response_serializer=ratelimit__pb2.CheckResponse.SerializeToString,
            ),
            'Peek': grpc.unary_unary_rpc_method_handler(
                    servicer.Peek,
                    request_deserializer=ratelimit__pb2.PeekRequest.FromString,
                    response_serializer=ratelimit__pb2.CheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ratelimit.v1.RateLimiter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ratelimit.v1.RateLimiter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RateLimiter:
    """A distributed rate-limiting service. Gateways and upstream services call
    `Check` before admitting a request; the limiter returns an allow/deny decision
    and reports how much of the budget remains. The decision must be cheap and
    fast — this sits on someone else's hot path.
    """

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ratelimit.v1.RateLimiter/Check',
            ratelimit__pb2.CheckRequest.SerializeToString,
            ratelimit__pb2.CheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Peek(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ratelimit.v1.RateLimiter/Peek',
            ratelimit__pb2.PeekRequest.SerializeToString,
            ratelimit__pb2.CheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
