"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
from . import ratelimit_pb2 as _ratelimit_pb2
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class RateLimiterStub:
    """A distributed rate-limiting service. Gateways and upstream services call
    `Check` before admitting a request; the limiter returns an allow/deny decision
    and reports how much of the budget remains. The decision must be cheap and
    fast — this sits on someone else's hot path.
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> RateLimiterAsyncStub: ...
    Check: _grpc.UnaryUnaryMultiCallable[_ratelimit_pb2.CheckRequest, _ratelimit_pb2.CheckResponse]
    """Atomically account for one request against `key` and return the decision.
    Consumes `cost` tokens of budget when allowed.
    """
    Peek: _grpc.UnaryUnaryMultiCallable[_ratelimit_pb2.PeekRequest, _ratelimit_pb2.CheckResponse]
    """Report the current state for `key` WITHOUT consuming budget — for
    dashboards, debugging, and "am I about to be limited?" probes.
    """

@_typing.type_check_only
class RateLimiterAsyncStub(RateLimiterStub):
    """A distributed rate-limiting service. Gateways and upstream services call
    `Check` before admitting a request; the limiter returns an allow/deny decision
    and reports how much of the budget remains. The decision must be cheap and
    fast — this sits on someone else's hot path.
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    Check: _aio.UnaryUnaryMultiCallable[_ratelimit_pb2.CheckRequest, _ratelimit_pb2.CheckResponse]  # type: ignore[assignment]
    """Atomically account for one request against `key` and return the decision.
    Consumes `cost` tokens of budget when allowed.
    """
    Peek: _aio.UnaryUnaryMultiCallable[_ratelimit_pb2.PeekRequest, _ratelimit_pb2.CheckResponse]  # type: ignore[assignment]
    """Report the current state for `key` WITHOUT consuming budget — for
    dashboards, debugging, and "am I about to be limited?" probes.
    """

class RateLimiterServicer(metaclass=_abc_1.ABCMeta):
    """A distributed rate-limiting service. Gateways and upstream services call
    `Check` before admitting a request; the limiter returns an allow/deny decision
    and reports how much of the budget remains. The decision must be cheap and
    fast — this sits on someone else's hot path.
    """

    @_abc_1.abstractmethod
    def Check(
        self,
        request: _ratelimit_pb2.CheckRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_ratelimit_pb2.CheckResponse, _abc.Awaitable[_ratelimit_pb2.CheckResponse]]:
        """Atomically account for one request against `key` and return the decision.
        Consumes `cost` tokens of budget when allowed.
        """

    @_abc_1.abstractmethod
    def Peek(
        self,
        request: _ratelimit_pb2.PeekRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_ratelimit_pb2.CheckResponse, _abc.Awaitable[_ratelimit_pb2.CheckResponse]]:
        """Report the current state for `key` WITHOUT consuming budget — for
        dashboards, debugging, and "am I about to be limited?" probes.
        """

def add_RateLimiterServicer_to_server(servicer: RateLimiterServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
