"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class CheckRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    KEY_FIELD_NUMBER: _builtins.int
    COST_FIELD_NUMBER: _builtins.int
    key: _builtins.str
    """The identity to limit on: an API key, user id, or client IP."""
    cost: _builtins.int
    """How many tokens this request should cost. 0 is treated as 1."""
    def __init__(
        self,
        *,
        key: _builtins.str = ...,
        cost: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["cost", b"cost", "key", b"key"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CheckRequest: _TypeAlias = CheckRequest  # noqa: Y015

@_typing.final
class PeekRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    KEY_FIELD_NUMBER: _builtins.int
    key: _builtins.str
    """The identity whose state to inspect."""
    def __init__(
        self,
        *,
        key: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PeekRequest: _TypeAlias = PeekRequest  # noqa: Y015

@_typing.final
class CheckResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ALLOWED_FIELD_NUMBER: _builtins.int
    REMAINING_FIELD_NUMBER: _builtins.int
    LIMIT_FIELD_NUMBER: _builtins.int
    RETRY_AFTER_MS_FIELD_NUMBER: _builtins.int
    allowed: _builtins.bool
    """Whether the request is permitted."""
    remaining: _builtins.int
    """Budget remaining in the current window after this decision."""
    limit: _builtins.int
    """The configured ceiling that applied (burst size / window limit)."""
    retry_after_ms: _builtins.int
    """If denied, how long the caller should wait before retrying, in milliseconds."""
    def __init__(
        self,
        *,
        allowed: _builtins.bool = ...,
        remaining: _builtins.int = ...,
        limit: _builtins.int = ...,
        retry_after_ms: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["allowed", b"allowed", "limit", b"limit", "remaining", b"remaining", "retry_after_ms", b"retry_after_ms"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CheckResponse: _TypeAlias = CheckResponse  # noqa: Y015
