# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ratelimit.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ratelimit.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fratelimit.proto\x12\x0cratelimit.v1\")\n\x0c\x43heckRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0c\n\x04\x63ost\x18\x02 \x01(\r\"\x1a\n\x0bPeekRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"Z\n\rCheckResponse\x12\x0f\n\x07\x61llowed\x18\x01 \x01(\x08\x12\x11\n\tremaining\x18\x02 \x01(\x04\x12\r\n\x05limit\x18\x03 \x01(\x04\x12\x16\n\x0eretry_after_ms\x18\x04 \x01(\x04\x32\x8f\x01\n\x0bRateLimiter\x12@\n\x05\x43heck\x12\x1a.ratelimit.v1.CheckRequest\x1a\x1b.ratelimit.v1.CheckResponse\x12>\n\x04Peek\x12\x19.ratelimit.v1.PeekRequest\x1a\x1b.ratelimit.v1.CheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ratelimit_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHECKREQUEST']._serialized_start=33
  _globals['_CHECKREQUEST']._serialized_end=74
  _globals['_PEEKREQUEST']._serialized_start=76
  _globals['_PEEKREQUEST']._serialized_end=102
  _globals['_CHECKRESPONSE']._serialized_start=104
  _globals['_CHECKRESPONSE']._serialized_end=194
  _globals['_RATELIMITER']._serialized_start=197
  _globals['_RATELIMITER']._serialized_end=340
# @@protoc_insertion_point(module_scope)
