# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import workflow_pb2 as workflow__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in workflow_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkflowServiceStub:
    """A minimal durable-workflow engine — the core of Temporal, rebuilt from scratch.

    Two kinds of client talk to this service:
    • starters — kick off and query executions (StartWorkflow, GetWorkflowResult);
    • workers  — long-poll for tasks, run the workflow function / activities, and
    report the outcome (PollWorkflowTask / RespondWorkflowTaskCompleted, plus the
    activity pair).

    The server owns the durable truth (each execution's event history) and hands
    workers just enough of it to make progress. Workers hold NO durable state — kill
    one mid-task and another picks the execution up by replaying its history. That is
    the whole promise of the engine: durable execution across crashes.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartWorkflow = channel.unary_unary(
                '/workflow.v1.WorkflowService/StartWorkflow',
                request_serializer=workflow__pb2.StartWorkflowRequest.SerializeToString,
                response_deserializer=workflow__pb2.StartWorkflowResponse.FromString,
                _registered_method=True)
        self.PollWorkflowTask = channel.unary_unary(
                '/workflow.v1.WorkflowService/PollWorkflowTask',
                request_serializer=workflow__pb2.PollWorkflowTaskRequest.SerializeToString,
                response_deserializer=workflow__pb2.PollWorkflowTaskResponse.FromString,
                _registered_method=True)
        self.RespondWorkflowTaskCompleted = channel.unary_unary(
                '/workflow.v1.WorkflowService/RespondWorkflowTaskCompleted',
                request_serializer=workflow__pb2.RespondWorkflowTaskCompletedRequest.SerializeToString,
                response_deserializer=workflow__pb2.RespondWorkflowTaskCompletedResponse.FromString,
                _registered_method=True)
        self.PollActivityTask = channel.unary_unary(
                '/workflow.v1.WorkflowService/PollActivityTask',
                request_serializer=workflow__pb2.PollActivityTaskRequest.SerializeToString,
                response_deserializer=workflow__pb2.PollActivityTaskResponse.FromString,
                _registered_method=True)
        self.RespondActivityTaskCompleted = channel.unary_unary(
                '/workflow.v1.WorkflowService/RespondActivityTaskCompleted',
                request_serializer=workflow__pb2.RespondActivityTaskCompletedRequest.SerializeToString,
                response_deserializer=workflow__pb2.RespondActivityTaskCompletedResponse.FromString,
                _registered_method=True)
        self.RespondActivityTaskFailed = channel.unary_unary(
                '/workflow.v1.WorkflowService/RespondActivityTaskFailed',
                request_serializer=workflow__pb2.RespondActivityTaskFailedRequest.SerializeToString,
                response_deserializer=workflow__pb2.RespondActivityTaskFailedResponse.FromString,
                _registered_method=True)
        self.GetWorkflowResult = channel.unary_unary(
                '/workflow.v1.WorkflowService/GetWorkflowResult',
                request_serializer=workflow__pb2.GetWorkflowResultRequest.SerializeToString,
                response_deserializer=workflow__pb2.GetWorkflowResultResponse.FromString,
                _registered_method=True)


class WorkflowServiceServicer:
    """A minimal durable-workflow engine — the core of Temporal, rebuilt from scratch.

    Two kinds of client talk to this service:
    • starters — kick off and query executions (StartWorkflow, GetWorkflowResult);
    • workers  — long-poll for tasks, run the workflow function / activities, and
    report the outcome (PollWorkflowTask / RespondWorkflowTaskCompleted, plus the
    activity pair).

    The server owns the durable truth (each execution's event history) and hands
    workers just enough of it to make progress. Workers hold NO durable state — kill
    one mid-task and another picks the execution up by replaying its history. That is
    the whole promise of the engine: durable execution across crashes.
    """

    def StartWorkflow(self, request, context):
        """Start a new execution: append WORKFLOW_STARTED to a fresh history and enqueue its
        first workflow task. Returns the run id that names this execution attempt.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PollWorkflowTask(self, request, context):
        """Long-poll for the next workflow task on `task_queue`. The response carries the
        history the worker must replay to rebuild state (V2) — or, on a sticky cache hit
        (V5), only the events appended since this worker last ran the execution.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RespondWorkflowTaskCompleted(self, request, context):
        """Report the commands the workflow produced this task (schedule an activity, start
        a timer, complete/fail the workflow). The server validates them against history
        for determinism (V2) and turns each into one or more events.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PollActivityTask(self, request, context):
        """Long-poll for the next activity task on `task_queue`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RespondActivityTaskCompleted(self, request, context):
        """Report an activity's result; the server appends ACTIVITY_COMPLETED and schedules
        a workflow task so the workflow can react to it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RespondActivityTaskFailed(self, request, context):
        """Report an activity failure; the server appends ACTIVITY_FAILED (the workflow may
        retry it or handle the error on its next task).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWorkflowResult(self, request, context):
        """Return the execution's current state — terminal result when done, or "running".
        Starters and tests use it to read the final answer.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkflowServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.StartWorkflow,
                    request_deserializer=workflow__pb2.StartWorkflowRequest.FromString,
                    response_serializer=workflow__pb2.StartWorkflowResponse.SerializeToString,
            ),
            'PollWorkflowTask': grpc.unary_unary_rpc_method_handler(
                    servicer.PollWorkflowTask,
                    request_deserializer=workflow__pb2.PollWorkflowTaskRequest.FromString,
                    response_serializer=workflow__pb2.PollWorkflowTaskResponse.SerializeToString,
            ),
            'RespondWorkflowTaskCompleted': grpc.unary_unary_rpc_method_handler(
                    servicer.RespondWorkflowTaskCompleted,
                    request_deserializer=workflow__pb2.RespondWorkflowTaskCompletedRequest.FromString,
                    response_serializer=workflow__pb2.RespondWorkflowTaskCompletedResponse.SerializeToString,
            ),
            'PollActivityTask': grpc.unary_unary_rpc_method_handler(
                    servicer.PollActivityTask,
                    request_deserializer=workflow__pb2.PollActivityTaskRequest.FromString,
                    response_serializer=workflow__pb2.PollActivityTaskResponse.SerializeToString,
            ),
            'RespondActivityTaskCompleted': grpc.unary_unary_rpc_method_handler(
                    servicer.RespondActivityTaskCompleted,
                    request_deserializer=workflow__pb2.RespondActivityTaskCompletedRequest.FromString,
                    response_serializer=workflow__pb2.RespondActivityTaskCompletedResponse.SerializeToString,
            ),
            'RespondActivityTaskFailed': grpc.unary_unary_rpc_method_handler(
                    servicer.RespondActivityTaskFailed,
                    request_deserializer=workflow__pb2.RespondActivityTaskFailedRequest.FromString,
                    response_serializer=workflow__pb2.RespondActivityTaskFailedResponse.SerializeToString,
            ),
            'GetWorkflowResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkflowResult,
                    request_deserializer=workflow__pb2.GetWorkflowResultRequest.FromString,
                    response_serializer=workflow__pb2.GetWorkflowResultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'workflow.v1.WorkflowService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('workflow.v1.WorkflowService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkflowService:
    """A minimal durable-workflow engine — the core of Temporal, rebuilt from scratch.

    Two kinds of client talk to this service:
    • starters — kick off and query executions (StartWorkflow, GetWorkflowResult);
    • workers  — long-poll for tasks, run the workflow function / activities, and
    report the outcome (PollWorkflowTask / RespondWorkflowTaskCompleted, plus the
    activity pair).

    The server owns the durable truth (each execution's event history) and hands
    workers just enough of it to make progress. Workers hold NO durable state — kill
    one mid-task and another picks the execution up by replaying its history. That is
    the whole promise of the engine: durable execution across crashes.
    """

    @staticmethod
    def StartWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workflow.v1.WorkflowService/StartWorkflow',
            workflow__pb2.StartWorkflowRequest.SerializeToString,
            workflow__pb2.StartWorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PollWorkflowTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workflow.v1.WorkflowService/PollWorkflowTask',
            workflow__pb2.PollWorkflowTaskRequest.SerializeToString,
            workflow__pb2.PollWorkflowTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RespondWorkflowTaskCompleted(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workflow.v1.WorkflowService/RespondWorkflowTaskCompleted',
            workflow__pb2.RespondWorkflowTaskCompletedRequest.SerializeToString,
            workflow__pb2.RespondWorkflowTaskCompletedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PollActivityTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workflow.v1.WorkflowService/PollActivityTask',
            workflow__pb2.PollActivityTaskRequest.SerializeToString,
            workflow__pb2.PollActivityTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RespondActivityTaskCompleted(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workflow.v1.WorkflowService/RespondActivityTaskCompleted',
            workflow__pb2.RespondActivityTaskCompletedRequest.SerializeToString,
            workflow__pb2.RespondActivityTaskCompletedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RespondActivityTaskFailed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workflow.v1.WorkflowService/RespondActivityTaskFailed',
            workflow__pb2.RespondActivityTaskFailedRequest.SerializeToString,
            workflow__pb2.RespondActivityTaskFailedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWorkflowResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workflow.v1.WorkflowService/GetWorkflowResult',
            workflow__pb2.GetWorkflowResultRequest.SerializeToString,
            workflow__pb2.GetWorkflowResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
