"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _EventType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _EventTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_EventType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    EVENT_TYPE_UNSPECIFIED: _EventType.ValueType  # 0
    WORKFLOW_STARTED: _EventType.ValueType  # 1
    WORKFLOW_TASK_SCHEDULED: _EventType.ValueType  # 2
    WORKFLOW_TASK_STARTED: _EventType.ValueType  # 3
    WORKFLOW_TASK_COMPLETED: _EventType.ValueType  # 4
    ACTIVITY_SCHEDULED: _EventType.ValueType  # 5
    ACTIVITY_STARTED: _EventType.ValueType  # 6
    ACTIVITY_COMPLETED: _EventType.ValueType  # 7
    ACTIVITY_FAILED: _EventType.ValueType  # 8
    TIMER_STARTED: _EventType.ValueType  # 9
    TIMER_FIRED: _EventType.ValueType  # 10
    WORKFLOW_COMPLETED: _EventType.ValueType  # 11
    WORKFLOW_FAILED: _EventType.ValueType  # 12

class EventType(_EventType, metaclass=_EventTypeEnumTypeWrapper):
    """---- history ----

    The kind of a history event. A history is an append-only log of these; folding it
    left-to-right reconstructs the execution's state (V1/V2).
    """

EVENT_TYPE_UNSPECIFIED: EventType.ValueType  # 0
WORKFLOW_STARTED: EventType.ValueType  # 1
WORKFLOW_TASK_SCHEDULED: EventType.ValueType  # 2
WORKFLOW_TASK_STARTED: EventType.ValueType  # 3
WORKFLOW_TASK_COMPLETED: EventType.ValueType  # 4
ACTIVITY_SCHEDULED: EventType.ValueType  # 5
ACTIVITY_STARTED: EventType.ValueType  # 6
ACTIVITY_COMPLETED: EventType.ValueType  # 7
ACTIVITY_FAILED: EventType.ValueType  # 8
TIMER_STARTED: EventType.ValueType  # 9
TIMER_FIRED: EventType.ValueType  # 10
WORKFLOW_COMPLETED: EventType.ValueType  # 11
WORKFLOW_FAILED: EventType.ValueType  # 12
Global___EventType: _TypeAlias = EventType  # noqa: Y015

class _CommandType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _CommandTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_CommandType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    COMMAND_TYPE_UNSPECIFIED: _CommandType.ValueType  # 0
    SCHEDULE_ACTIVITY: _CommandType.ValueType  # 1
    START_TIMER: _CommandType.ValueType  # 2
    COMPLETE_WORKFLOW: _CommandType.ValueType  # 3
    FAIL_WORKFLOW: _CommandType.ValueType  # 4

class CommandType(_CommandType, metaclass=_CommandTypeEnumTypeWrapper):
    """---- commands ----"""

COMMAND_TYPE_UNSPECIFIED: CommandType.ValueType  # 0
SCHEDULE_ACTIVITY: CommandType.ValueType  # 1
START_TIMER: CommandType.ValueType  # 2
COMPLETE_WORKFLOW: CommandType.ValueType  # 3
FAIL_WORKFLOW: CommandType.ValueType  # 4
Global___CommandType: _TypeAlias = CommandType  # noqa: Y015

@_typing.final
class HistoryEvent(_message.Message):
    """One entry in an execution's history. `event_id` is monotonic per run and defines
    the replay order; `attributes` is the event-type-specific payload (JSON bytes).
    """

    DESCRIPTOR: _descriptor.Descriptor

    EVENT_ID_FIELD_NUMBER: _builtins.int
    EVENT_TYPE_FIELD_NUMBER: _builtins.int
    TIMESTAMP_MS_FIELD_NUMBER: _builtins.int
    ATTRIBUTES_FIELD_NUMBER: _builtins.int
    event_id: _builtins.int
    event_type: Global___EventType.ValueType
    timestamp_ms: _builtins.int
    attributes: _builtins.bytes
    def __init__(
        self,
        *,
        event_id: _builtins.int = ...,
        event_type: Global___EventType.ValueType = ...,
        timestamp_ms: _builtins.int = ...,
        attributes: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["attributes", b"attributes", "event_id", b"event_id", "event_type", b"event_type", "timestamp_ms", b"timestamp_ms"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___HistoryEvent: _TypeAlias = HistoryEvent  # noqa: Y015

@_typing.final
class Command(_message.Message):
    """A decision the workflow made on its most recent task. The server validates the
    command stream against the replayed history (determinism, V2) and turns each into
    events + the side effects they imply (an activity task, a durable timer, …).
    """

    DESCRIPTOR: _descriptor.Descriptor

    COMMAND_TYPE_FIELD_NUMBER: _builtins.int
    ACTIVITY_TYPE_FIELD_NUMBER: _builtins.int
    ACTIVITY_INPUT_FIELD_NUMBER: _builtins.int
    TIMER_ID_FIELD_NUMBER: _builtins.int
    TIMER_DELAY_MS_FIELD_NUMBER: _builtins.int
    RESULT_FIELD_NUMBER: _builtins.int
    FAILURE_FIELD_NUMBER: _builtins.int
    command_type: Global___CommandType.ValueType
    activity_type: _builtins.str
    """SCHEDULE_ACTIVITY"""
    activity_input: _builtins.bytes
    timer_id: _builtins.str
    """START_TIMER"""
    timer_delay_ms: _builtins.int
    result: _builtins.bytes
    """COMPLETE_WORKFLOW / FAIL_WORKFLOW"""
    failure: _builtins.str
    def __init__(
        self,
        *,
        command_type: Global___CommandType.ValueType = ...,
        activity_type: _builtins.str = ...,
        activity_input: _builtins.bytes = ...,
        timer_id: _builtins.str = ...,
        timer_delay_ms: _builtins.int = ...,
        result: _builtins.bytes = ...,
        failure: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["activity_input", b"activity_input", "activity_type", b"activity_type", "command_type", b"command_type", "failure", b"failure", "result", b"result", "timer_delay_ms", b"timer_delay_ms", "timer_id", b"timer_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Command: _TypeAlias = Command  # noqa: Y015

@_typing.final
class StartWorkflowRequest(_message.Message):
    """---- rpc messages ----"""

    DESCRIPTOR: _descriptor.Descriptor

    WORKFLOW_TYPE_FIELD_NUMBER: _builtins.int
    WORKFLOW_ID_FIELD_NUMBER: _builtins.int
    TASK_QUEUE_FIELD_NUMBER: _builtins.int
    INPUT_FIELD_NUMBER: _builtins.int
    workflow_type: _builtins.str
    workflow_id: _builtins.str
    """Caller-chosen id for the logical workflow; the reuse policy (reject a duplicate?
    start a new run?) is yours to define.
    """
    task_queue: _builtins.str
    input: _builtins.bytes
    def __init__(
        self,
        *,
        workflow_type: _builtins.str = ...,
        workflow_id: _builtins.str = ...,
        task_queue: _builtins.str = ...,
        input: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["input", b"input", "task_queue", b"task_queue", "workflow_id", b"workflow_id", "workflow_type", b"workflow_type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StartWorkflowRequest: _TypeAlias = StartWorkflowRequest  # noqa: Y015

@_typing.final
class StartWorkflowResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_ID_FIELD_NUMBER: _builtins.int
    run_id: _builtins.str
    def __init__(
        self,
        *,
        run_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["run_id", b"run_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StartWorkflowResponse: _TypeAlias = StartWorkflowResponse  # noqa: Y015

@_typing.final
class PollWorkflowTaskRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TASK_QUEUE_FIELD_NUMBER: _builtins.int
    IDENTITY_FIELD_NUMBER: _builtins.int
    task_queue: _builtins.str
    identity: _builtins.str
    """Worker identity — the key sticky routing (V5) uses to send an execution back to
    the worker that still has its state cached.
    """
    def __init__(
        self,
        *,
        task_queue: _builtins.str = ...,
        identity: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["identity", b"identity", "task_queue", b"task_queue"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PollWorkflowTaskRequest: _TypeAlias = PollWorkflowTaskRequest  # noqa: Y015

@_typing.final
class PollWorkflowTaskResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TASK_TOKEN_FIELD_NUMBER: _builtins.int
    WORKFLOW_ID_FIELD_NUMBER: _builtins.int
    RUN_ID_FIELD_NUMBER: _builtins.int
    HISTORY_FIELD_NUMBER: _builtins.int
    STICKY_CACHE_HIT_FIELD_NUMBER: _builtins.int
    task_token: _builtins.bytes
    """Opaque token that authorizes exactly one RespondWorkflowTaskCompleted. An EMPTY
    token means the long-poll timed out with no work — the worker should poll again.
    """
    workflow_id: _builtins.str
    run_id: _builtins.str
    sticky_cache_hit: _builtins.bool
    @_builtins.property
    def history(self) -> _containers.RepeatedCompositeFieldContainer[Global___HistoryEvent]:
        """The history to replay. On a sticky hit this is only the events appended since the
        worker last ran this execution (V5); otherwise it is the full history (V2).
        """

    def __init__(
        self,
        *,
        task_token: _builtins.bytes = ...,
        workflow_id: _builtins.str = ...,
        run_id: _builtins.str = ...,
        history: _abc.Iterable[Global___HistoryEvent] | None = ...,
        sticky_cache_hit: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["history", b"history", "run_id", b"run_id", "sticky_cache_hit", b"sticky_cache_hit", "task_token", b"task_token", "workflow_id", b"workflow_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PollWorkflowTaskResponse: _TypeAlias = PollWorkflowTaskResponse  # noqa: Y015

@_typing.final
class RespondWorkflowTaskCompletedRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TASK_TOKEN_FIELD_NUMBER: _builtins.int
    COMMANDS_FIELD_NUMBER: _builtins.int
    task_token: _builtins.bytes
    @_builtins.property
    def commands(self) -> _containers.RepeatedCompositeFieldContainer[Global___Command]: ...
    def __init__(
        self,
        *,
        task_token: _builtins.bytes = ...,
        commands: _abc.Iterable[Global___Command] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["commands", b"commands", "task_token", b"task_token"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RespondWorkflowTaskCompletedRequest: _TypeAlias = RespondWorkflowTaskCompletedRequest  # noqa: Y015

@_typing.final
class RespondWorkflowTaskCompletedResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RespondWorkflowTaskCompletedResponse: _TypeAlias = RespondWorkflowTaskCompletedResponse  # noqa: Y015

@_typing.final
class PollActivityTaskRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TASK_QUEUE_FIELD_NUMBER: _builtins.int
    IDENTITY_FIELD_NUMBER: _builtins.int
    task_queue: _builtins.str
    identity: _builtins.str
    def __init__(
        self,
        *,
        task_queue: _builtins.str = ...,
        identity: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["identity", b"identity", "task_queue", b"task_queue"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PollActivityTaskRequest: _TypeAlias = PollActivityTaskRequest  # noqa: Y015

@_typing.final
class PollActivityTaskResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TASK_TOKEN_FIELD_NUMBER: _builtins.int
    ACTIVITY_TYPE_FIELD_NUMBER: _builtins.int
    INPUT_FIELD_NUMBER: _builtins.int
    WORKFLOW_ID_FIELD_NUMBER: _builtins.int
    RUN_ID_FIELD_NUMBER: _builtins.int
    task_token: _builtins.bytes
    """Empty token = long-poll timed out with no work."""
    activity_type: _builtins.str
    input: _builtins.bytes
    workflow_id: _builtins.str
    run_id: _builtins.str
    def __init__(
        self,
        *,
        task_token: _builtins.bytes = ...,
        activity_type: _builtins.str = ...,
        input: _builtins.bytes = ...,
        workflow_id: _builtins.str = ...,
        run_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["activity_type", b"activity_type", "input", b"input", "run_id", b"run_id", "task_token", b"task_token", "workflow_id", b"workflow_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PollActivityTaskResponse: _TypeAlias = PollActivityTaskResponse  # noqa: Y015

@_typing.final
class RespondActivityTaskCompletedRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TASK_TOKEN_FIELD_NUMBER: _builtins.int
    RESULT_FIELD_NUMBER: _builtins.int
    task_token: _builtins.bytes
    result: _builtins.bytes
    def __init__(
        self,
        *,
        task_token: _builtins.bytes = ...,
        result: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["result", b"result", "task_token", b"task_token"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RespondActivityTaskCompletedRequest: _TypeAlias = RespondActivityTaskCompletedRequest  # noqa: Y015

@_typing.final
class RespondActivityTaskCompletedResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RespondActivityTaskCompletedResponse: _TypeAlias = RespondActivityTaskCompletedResponse  # noqa: Y015

@_typing.final
class RespondActivityTaskFailedRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TASK_TOKEN_FIELD_NUMBER: _builtins.int
    FAILURE_FIELD_NUMBER: _builtins.int
    task_token: _builtins.bytes
    failure: _builtins.str
    def __init__(
        self,
        *,
        task_token: _builtins.bytes = ...,
        failure: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["failure", b"failure", "task_token", b"task_token"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RespondActivityTaskFailedRequest: _TypeAlias = RespondActivityTaskFailedRequest  # noqa: Y015

@_typing.final
class RespondActivityTaskFailedResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RespondActivityTaskFailedResponse: _TypeAlias = RespondActivityTaskFailedResponse  # noqa: Y015

@_typing.final
class GetWorkflowResultRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    WORKFLOW_ID_FIELD_NUMBER: _builtins.int
    RUN_ID_FIELD_NUMBER: _builtins.int
    workflow_id: _builtins.str
    run_id: _builtins.str
    def __init__(
        self,
        *,
        workflow_id: _builtins.str = ...,
        run_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["run_id", b"run_id", "workflow_id", b"workflow_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetWorkflowResultRequest: _TypeAlias = GetWorkflowResultRequest  # noqa: Y015

@_typing.final
class GetWorkflowResultResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUNNING_FIELD_NUMBER: _builtins.int
    COMPLETED_FIELD_NUMBER: _builtins.int
    RESULT_FIELD_NUMBER: _builtins.int
    FAILURE_FIELD_NUMBER: _builtins.int
    running: _builtins.bool
    """Terminal outcome. `running` true means the execution has not finished yet."""
    completed: _builtins.bool
    result: _builtins.bytes
    failure: _builtins.str
    def __init__(
        self,
        *,
        running: _builtins.bool = ...,
        completed: _builtins.bool = ...,
        result: _builtins.bytes = ...,
        failure: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["completed", b"completed", "failure", b"failure", "result", b"result", "running", b"running"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetWorkflowResultResponse: _TypeAlias = GetWorkflowResultResponse  # noqa: Y015
