"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing
from . import workflow_pb2 as _workflow_pb2

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class WorkflowServiceStub:
    """A minimal durable-workflow engine — the core of Temporal, rebuilt from scratch.

    Two kinds of client talk to this service:
      • starters — kick off and query executions (StartWorkflow, GetWorkflowResult);
      • workers  — long-poll for tasks, run the workflow function / activities, and
        report the outcome (PollWorkflowTask / RespondWorkflowTaskCompleted, plus the
        activity pair).

    The server owns the durable truth (each execution's event history) and hands
    workers just enough of it to make progress. Workers hold NO durable state — kill
    one mid-task and another picks the execution up by replaying its history. That is
    the whole promise of the engine: durable execution across crashes.
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> WorkflowServiceAsyncStub: ...
    StartWorkflow: _grpc.UnaryUnaryMultiCallable[_workflow_pb2.StartWorkflowRequest, _workflow_pb2.StartWorkflowResponse]
    """Start a new execution: append WORKFLOW_STARTED to a fresh history and enqueue its
    first workflow task. Returns the run id that names this execution attempt.
    """
    PollWorkflowTask: _grpc.UnaryUnaryMultiCallable[_workflow_pb2.PollWorkflowTaskRequest, _workflow_pb2.PollWorkflowTaskResponse]
    """Long-poll for the next workflow task on `task_queue`. The response carries the
    history the worker must replay to rebuild state (V2) — or, on a sticky cache hit
    (V5), only the events appended since this worker last ran the execution.
    """
    RespondWorkflowTaskCompleted: _grpc.UnaryUnaryMultiCallable[_workflow_pb2.RespondWorkflowTaskCompletedRequest, _workflow_pb2.RespondWorkflowTaskCompletedResponse]
    """Report the commands the workflow produced this task (schedule an activity, start
    a timer, complete/fail the workflow). The server validates them against history
    for determinism (V2) and turns each into one or more events.
    """
    PollActivityTask: _grpc.UnaryUnaryMultiCallable[_workflow_pb2.PollActivityTaskRequest, _workflow_pb2.PollActivityTaskResponse]
    """Long-poll for the next activity task on `task_queue`."""
    RespondActivityTaskCompleted: _grpc.UnaryUnaryMultiCallable[_workflow_pb2.RespondActivityTaskCompletedRequest, _workflow_pb2.RespondActivityTaskCompletedResponse]
    """Report an activity's result; the server appends ACTIVITY_COMPLETED and schedules
    a workflow task so the workflow can react to it.
    """
    RespondActivityTaskFailed: _grpc.UnaryUnaryMultiCallable[_workflow_pb2.RespondActivityTaskFailedRequest, _workflow_pb2.RespondActivityTaskFailedResponse]
    """Report an activity failure; the server appends ACTIVITY_FAILED (the workflow may
    retry it or handle the error on its next task).
    """
    GetWorkflowResult: _grpc.UnaryUnaryMultiCallable[_workflow_pb2.GetWorkflowResultRequest, _workflow_pb2.GetWorkflowResultResponse]
    """Return the execution's current state — terminal result when done, or "running".
    Starters and tests use it to read the final answer.
    """

@_typing.type_check_only
class WorkflowServiceAsyncStub(WorkflowServiceStub):
    """A minimal durable-workflow engine — the core of Temporal, rebuilt from scratch.

    Two kinds of client talk to this service:
      • starters — kick off and query executions (StartWorkflow, GetWorkflowResult);
      • workers  — long-poll for tasks, run the workflow function / activities, and
        report the outcome (PollWorkflowTask / RespondWorkflowTaskCompleted, plus the
        activity pair).

    The server owns the durable truth (each execution's event history) and hands
    workers just enough of it to make progress. Workers hold NO durable state — kill
    one mid-task and another picks the execution up by replaying its history. That is
    the whole promise of the engine: durable execution across crashes.
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    StartWorkflow: _aio.UnaryUnaryMultiCallable[_workflow_pb2.StartWorkflowRequest, _workflow_pb2.StartWorkflowResponse]  # type: ignore[assignment]
    """Start a new execution: append WORKFLOW_STARTED to a fresh history and enqueue its
    first workflow task. Returns the run id that names this execution attempt.
    """
    PollWorkflowTask: _aio.UnaryUnaryMultiCallable[_workflow_pb2.PollWorkflowTaskRequest, _workflow_pb2.PollWorkflowTaskResponse]  # type: ignore[assignment]
    """Long-poll for the next workflow task on `task_queue`. The response carries the
    history the worker must replay to rebuild state (V2) — or, on a sticky cache hit
    (V5), only the events appended since this worker last ran the execution.
    """
    RespondWorkflowTaskCompleted: _aio.UnaryUnaryMultiCallable[_workflow_pb2.RespondWorkflowTaskCompletedRequest, _workflow_pb2.RespondWorkflowTaskCompletedResponse]  # type: ignore[assignment]
    """Report the commands the workflow produced this task (schedule an activity, start
    a timer, complete/fail the workflow). The server validates them against history
    for determinism (V2) and turns each into one or more events.
    """
    PollActivityTask: _aio.UnaryUnaryMultiCallable[_workflow_pb2.PollActivityTaskRequest, _workflow_pb2.PollActivityTaskResponse]  # type: ignore[assignment]
    """Long-poll for the next activity task on `task_queue`."""
    RespondActivityTaskCompleted: _aio.UnaryUnaryMultiCallable[_workflow_pb2.RespondActivityTaskCompletedRequest, _workflow_pb2.RespondActivityTaskCompletedResponse]  # type: ignore[assignment]
    """Report an activity's result; the server appends ACTIVITY_COMPLETED and schedules
    a workflow task so the workflow can react to it.
    """
    RespondActivityTaskFailed: _aio.UnaryUnaryMultiCallable[_workflow_pb2.RespondActivityTaskFailedRequest, _workflow_pb2.RespondActivityTaskFailedResponse]  # type: ignore[assignment]
    """Report an activity failure; the server appends ACTIVITY_FAILED (the workflow may
    retry it or handle the error on its next task).
    """
    GetWorkflowResult: _aio.UnaryUnaryMultiCallable[_workflow_pb2.GetWorkflowResultRequest, _workflow_pb2.GetWorkflowResultResponse]  # type: ignore[assignment]
    """Return the execution's current state — terminal result when done, or "running".
    Starters and tests use it to read the final answer.
    """

class WorkflowServiceServicer(metaclass=_abc_1.ABCMeta):
    """A minimal durable-workflow engine — the core of Temporal, rebuilt from scratch.

    Two kinds of client talk to this service:
      • starters — kick off and query executions (StartWorkflow, GetWorkflowResult);
      • workers  — long-poll for tasks, run the workflow function / activities, and
        report the outcome (PollWorkflowTask / RespondWorkflowTaskCompleted, plus the
        activity pair).

    The server owns the durable truth (each execution's event history) and hands
    workers just enough of it to make progress. Workers hold NO durable state — kill
    one mid-task and another picks the execution up by replaying its history. That is
    the whole promise of the engine: durable execution across crashes.
    """

    @_abc_1.abstractmethod
    def StartWorkflow(
        self,
        request: _workflow_pb2.StartWorkflowRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_workflow_pb2.StartWorkflowResponse, _abc.Awaitable[_workflow_pb2.StartWorkflowResponse]]:
        """Start a new execution: append WORKFLOW_STARTED to a fresh history and enqueue its
        first workflow task. Returns the run id that names this execution attempt.
        """

    @_abc_1.abstractmethod
    def PollWorkflowTask(
        self,
        request: _workflow_pb2.PollWorkflowTaskRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_workflow_pb2.PollWorkflowTaskResponse, _abc.Awaitable[_workflow_pb2.PollWorkflowTaskResponse]]:
        """Long-poll for the next workflow task on `task_queue`. The response carries the
        history the worker must replay to rebuild state (V2) — or, on a sticky cache hit
        (V5), only the events appended since this worker last ran the execution.
        """

    @_abc_1.abstractmethod
    def RespondWorkflowTaskCompleted(
        self,
        request: _workflow_pb2.RespondWorkflowTaskCompletedRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_workflow_pb2.RespondWorkflowTaskCompletedResponse, _abc.Awaitable[_workflow_pb2.RespondWorkflowTaskCompletedResponse]]:
        """Report the commands the workflow produced this task (schedule an activity, start
        a timer, complete/fail the workflow). The server validates them against history
        for determinism (V2) and turns each into one or more events.
        """

    @_abc_1.abstractmethod
    def PollActivityTask(
        self,
        request: _workflow_pb2.PollActivityTaskRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_workflow_pb2.PollActivityTaskResponse, _abc.Awaitable[_workflow_pb2.PollActivityTaskResponse]]:
        """Long-poll for the next activity task on `task_queue`."""

    @_abc_1.abstractmethod
    def RespondActivityTaskCompleted(
        self,
        request: _workflow_pb2.RespondActivityTaskCompletedRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_workflow_pb2.RespondActivityTaskCompletedResponse, _abc.Awaitable[_workflow_pb2.RespondActivityTaskCompletedResponse]]:
        """Report an activity's result; the server appends ACTIVITY_COMPLETED and schedules
        a workflow task so the workflow can react to it.
        """

    @_abc_1.abstractmethod
    def RespondActivityTaskFailed(
        self,
        request: _workflow_pb2.RespondActivityTaskFailedRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_workflow_pb2.RespondActivityTaskFailedResponse, _abc.Awaitable[_workflow_pb2.RespondActivityTaskFailedResponse]]:
        """Report an activity failure; the server appends ACTIVITY_FAILED (the workflow may
        retry it or handle the error on its next task).
        """

    @_abc_1.abstractmethod
    def GetWorkflowResult(
        self,
        request: _workflow_pb2.GetWorkflowResultRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_workflow_pb2.GetWorkflowResultResponse, _abc.Awaitable[_workflow_pb2.GetWorkflowResultResponse]]:
        """Return the execution's current state — terminal result when done, or "running".
        Starters and tests use it to read the final answer.
        """

def add_WorkflowServiceServicer_to_server(servicer: WorkflowServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
