#!/usr/bin/env python3
"""transcode-pipeline — local dev task runner.

A wrapper around the day-to-day commands for this project: uv, the docker-compose
Postgres, migrations, a generated test source, and probes that make each vertical
visible. The `Makefile` shells out to this file so there is one source of truth
with colors, emojis and readable output. Help tables use `tools/makefile_help.py`.

The probes follow the SPEC's suggested order of attack:

* `make fixture` — a real source to cut: generated by ffmpeg, no download.
* `make probe`   — V1's input made visible: the keyframes and duration
                   `plan_chunks` will plan against, via the wired `ffmpeg.py`.
* `make submit`  — V2 made visible: `POST /jobs` for the fixture.
* `make job`     — `GET /jobs/$JOB`, the DAG draining (once V2 exists).

On the bare scaffold `submit` answers `501` with the todo that blocks it, which is
the fastest way to see which vertical you are on.

Usage:
    python3 makefile.py <task> [task ...]
    make <task>            # via the Makefile wrapper
"""

from __future__ import annotations

import json
import os
import sys
import urllib.error
import urllib.request
from pathlib import Path

PROJECT_DIR = Path(__file__).resolve().parent
if str(PROJECT_DIR.parent.parent / "tools") not in sys.path:
    sys.path.insert(0, str(PROJECT_DIR.parent.parent / "tools"))

from makefile_runner import (  # noqa: E402
    C,
    make_runner,
    register_compose_lifecycle,
    register_help,
    register_md,
    register_python_checks,
    register_python_run,
    register_setup,
)

DEFAULT_SOURCE = "bbb.mp4"
"""The file `make fixture` writes under WORK_DIR, and what `make submit` names."""

runner = make_runner(
    crate="transcode-pipeline",
    help_title="🎞️ transcode-pipeline (chunk · DAG · parallel workers · stitch)",
    project_dir=PROJECT_DIR,
    default_port="8080",
    help_footers=[
        ("Typical first run", "make setup && make sync && make dev"),
        ("Make a source to cut", "make fixture && make probe"),
        ("Submit it (V2)", "make submit"),
        ("Run the worker pool", "make workers"),
        ("Run all checks", "make verify"),
    ],
)

register_setup(runner)
register_python_checks(runner)
register_compose_lifecycle(runner)
register_python_run(runner)


@runner.task("sync", "📦", "Setup", "Install/refresh the virtualenv from uv.lock")
def sync() -> None:
    runner.step("📦", "syncing dependencies…")
    runner.uv("sync")
    runner.ok("environment ready")


def _env() -> dict[str, str]:
    return runner.load_dotenv()


def _url(path: str = "") -> str:
    port = _env().get("PORT", runner.config.default_port)
    return f"http://localhost:{port}{path}"


def _work_dir() -> Path:
    return runner.project_dir / _env().get("WORK_DIR", "./work")


def _source() -> str:
    return os.environ.get("SOURCE", DEFAULT_SOURCE)


def _request(url: str, *, body: object | None = None) -> tuple[int, str]:
    data = json.dumps(body).encode() if body is not None else None
    request = urllib.request.Request(url, data=data, method="POST" if data else "GET")
    if data is not None:
        request.add_header("content-type", "application/json")
    try:
        with urllib.request.urlopen(request, timeout=5) as resp:
            return resp.status, resp.read().decode("utf-8", "replace")
    except urllib.error.HTTPError as exc:
        return exc.code, exc.read().decode("utf-8", "replace")
    except OSError as exc:
        return 0, str(exc)


def _report(code: int, body: str) -> None:
    if code == 0:
        runner.fail(f"no answer — is the server running? ({body})")
        sys.exit(1)
    color = C.GREEN if code < 400 else C.YELLOW if code == 501 else C.RED
    print(f"  {color}{code}{C.RESET}  {body.strip()}")
    if code == 501:
        print(f"   {C.DIM}that todo is the worklist{C.RESET}")
    print()


# --------------------------------------------------------------------------- #
# Services
# --------------------------------------------------------------------------- #


@runner.task("up", "🐳", "Services", "Start postgres and wait until healthy")
def up() -> None:
    runner.step("🐳", "starting postgres…")
    # `--wait` blocks on the compose healthcheck, so this returns only once
    # Postgres actually accepts connections — not merely once it started.
    runner.run([*runner.compose, "up", "-d", "--wait"], cwd=runner.project_dir)
    runner.ok("postgres healthy → :5412")


@runner.task("deps", "🐳", "Services", "Alias for `up`")
def deps() -> None:
    up()


@runner.task("migrate", "🗃️", "Services", "Apply SQL migrations")
def migrate() -> None:
    """The Python answer to `sqlx migrate run` — see `transcode_pipeline.migrate`."""
    runner.step("🗃️", "applying migrations…")
    runner.uv(
        "run",
        "python",
        "-m",
        "transcode_pipeline.migrate",
        str(runner.project_dir / "migrations"),
        env=_env(),
    )
    runner.ok("migrations applied")


@runner.task("reset-db", "💥", "Services", "Drop volumes, recreate, migrate (destructive)")
def reset_db() -> None:
    runner.warn("dropping volumes — this wipes every job, task and edge")
    runner.run([*runner.compose, "down", "-v"], cwd=runner.project_dir, check=False)
    up()
    migrate()


# --------------------------------------------------------------------------- #
# Run
# --------------------------------------------------------------------------- #


@runner.task("workers", "⚙️", "Run", "Run with RUN_WORKERS=true (scheduler + worker pool)")
def workers() -> None:
    """The scheduler and workers call V2/V3 store methods on their first tick, so on
    the scaffold each one dies and logs the todo that stopped it."""
    runner.step("⚙️", f"starting {runner.crate} with the worker pool…")
    runner.uv("run", runner.crate, env={**_env(), "RUN_WORKERS": "true"})


@runner.task("dev", "🚀", "Run", "Postgres up, migrate, then run the server")
def dev() -> None:
    deps()
    migrate()
    runner.tasks["run"][0]()


@runner.task("smoke", "🔥", "Run", "Hit /healthz (server must be running)")
def smoke() -> None:
    runner.step("🔥", f"GET {_url('/healthz')}")
    code, body = _request(_url("/healthz"))
    if code == 200:
        runner.ok(f"healthz OK ({body.strip()})")
    else:
        runner.fail(f"healthz failed ({code}) — is the server running?")
        sys.exit(1)


# --------------------------------------------------------------------------- #
# Probes
# --------------------------------------------------------------------------- #


@runner.task("fixture", "🎬", "Probe", f"Generate $WORK_DIR/{DEFAULT_SOURCE} (SECS=120 GOP=60)")
def fixture() -> None:
    """A synthetic source: test-pattern video plus a sine tone, H.264 + AAC.

    `GOP` fixes the keyframe interval in frames (30 fps, so 60 = one keyframe every
    2 s) and `-sc_threshold 0` stops the encoder inserting extra keyframes at scene
    cuts. That makes the keyframe grid perfectly regular, which is the *easy* case
    for V1: real uploads have irregular GOPs. Try a few GOP values against the same
    TARGET_CHUNK_SECS before you trust your planner.
    """
    runner.require("ffmpeg", "Install ffmpeg (a static build in ~/.local/bin works).")
    secs = os.environ.get("SECS", "120")
    gop = os.environ.get("GOP", "60")
    out = _work_dir() / _source()
    out.parent.mkdir(parents=True, exist_ok=True)
    runner.step("🎬", f"encoding {secs}s @30fps, keyframe every {gop} frames → {out}")
    runner.run(
        [
            _env().get("FFMPEG_BIN", "ffmpeg"),
            "-y",
            "-hide_banner",
            "-loglevel",
            "error",
            "-f",
            "lavfi",
            "-i",
            "testsrc2=size=1280x720:rate=30",
            "-f",
            "lavfi",
            "-i",
            "sine=frequency=440:sample_rate=48000",
            "-t",
            secs,
            "-c:v",
            "libx264",
            "-preset",
            "veryfast",
            "-g",
            gop,
            "-keyint_min",
            gop,
            "-sc_threshold",
            "0",
            "-pix_fmt",
            "yuv420p",
            "-c:a",
            "aac",
            "-b:a",
            "128k",
            str(out),
        ]
    )
    runner.ok(f"wrote {out}")


@runner.task("probe", "🔍", "Probe", "V1's input: keyframes + duration of $SOURCE")
def probe() -> None:
    """Runs the wired `ffmpeg.probe_keyframes` / `probe_duration` — the exact
    values `plan_chunks` receives, not a hand-typed ffprobe that might differ."""
    source = _work_dir() / _source()
    if not source.is_file():
        runner.fail(f"{source} not found — run `make fixture` first")
        sys.exit(1)
    env = _env()
    # A standalone ffmpeg build often ships without ffprobe; say so up front rather
    # than surfacing it as a spawn traceback from inside `ffmpeg.py`.
    runner.require(
        env.get("FFPROBE_BIN", "ffprobe"),
        "Install it next to ffmpeg, or point FFPROBE_BIN at one.",
    )
    script = (
        "import asyncio, sys\n"
        "from transcode_pipeline import ffmpeg\n"
        "async def main():\n"
        "    kf = await ffmpeg.probe_keyframes(sys.argv[1], sys.argv[2])\n"
        "    d = await ffmpeg.probe_duration(sys.argv[1], sys.argv[2])\n"
        "    head = ', '.join(f'{t:.3f}' for t in kf[:8])\n"
        "    print(f'  duration   {d:.3f}s')\n"
        '    print(f\'  keyframes  {len(kf)}  [{head}{", …" if len(kf) > 8 else ""}]\')\n'
        "asyncio.run(main())\n"
    )
    runner.step("🔍", f"probing {source}")
    runner.uv(
        "run", "python", "-c", script, env.get("FFPROBE_BIN", "ffprobe"), str(source), env=env
    )
    print()


@runner.task("submit", "📤", "Probe", "POST /jobs for $SOURCE (V2)")
def submit() -> None:
    runner.step("📤", f"POST {_url('/jobs')}  source={_source()}")
    _report(*_request(_url("/jobs"), body={"source": _source()}))


@runner.task("job", "📋", "Probe", "GET /jobs/$JOB — status + task counts (V2)")
def job() -> None:
    job_id = os.environ.get("JOB")
    if not job_id:
        runner.fail("set JOB=<id> — the id `make submit` returned")
        sys.exit(1)
    runner.step("📋", f"GET {_url(f'/jobs/{job_id}')}")
    _report(*_request(_url(f"/jobs/{job_id}")))


@runner.task("metrics", "📈", "Probe", "GET /metrics — the transcode_* series")
def metrics() -> None:
    code, body = _request(_url("/metrics"))
    if code == 0:
        runner.fail("no answer — is the server running?")
        sys.exit(1)
    lines = [ln for ln in body.splitlines() if ln.startswith("transcode_")]
    if not lines:
        runner.warn("no transcode_* series yet — declaring them is the Observability checklist")
        return
    for line in lines:
        print(f"  {line}")
    print()
    runner.ok(f"{len(lines)} pipeline metric series")


# --------------------------------------------------------------------------- #
# The boss fight
# --------------------------------------------------------------------------- #


@runner.task("bench", "🐉", "Bench", "The Straggler: speedup vs workers + a kill -9 mid-job")
def bench() -> None:
    """The boss fight's harness — building it is part of the fight.

    Three runs over one multi-minute source and a 3-rendition ladder: a 1-worker
    serial baseline, 8 workers, and 8 workers with one `kill -9`'d mid-transcode.
    """
    runner.warn("bench/ is yours to build — see the 🐉 Boss fight in SPEC.md")
    print(f"   {C.DIM}make fixture SECS=600   # a multi-minute source{C.RESET}")
    print(f"   {C.DIM}make md                 # read the Arena + 'the boss falls when'{C.RESET}")


@runner.task("profile", "🔥", "Bench", "Sample the running server with py-spy (10s flamegraph)")
def profile() -> None:
    """The Definition-of-done profiling gate.

    py-spy attaches to a *running* process by PID, so start the workers, submit a
    real job, and sample while it drains — a flamegraph of an idle loop tells you
    nothing. Expect most wall-clock inside ffmpeg children py-spy cannot see; what
    it shows is the orchestration overhead, which is exactly the question.
    """
    out = runner.project_dir / "docs" / "flamegraph.svg"
    out.parent.mkdir(parents=True, exist_ok=True)
    pid = os.environ.get("PID")
    if not pid:
        runner.fail("set PID=<server pid> — py-spy samples a running process")
        print(f"   {C.DIM}e.g. `PID=$(pgrep -f transcode-pipeline) make profile`{C.RESET}")
        sys.exit(1)
    runner.step("🔥", "sampling for 10s — keep a job draining meanwhile")
    runner.uv("run", "py-spy", "record", "--duration", "10", "--pid", pid, "--output", str(out))
    runner.ok(f"wrote {out}")


register_md(runner)
register_help(runner)

if __name__ == "__main__":
    runner.entrypoint(sys.argv[1:])
